config/routes.rb
Rails.application.routes.draw do



  resources :students, only: [:show, :new, :index, :create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  root 'students#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :email, :name, :dob, presence: true

  # student must be over 18 yrs Date.today - 18.years > dob
  validate :must_be_eighteen

  # emails must be unique
  validates :email, uniqueness: true
  # students name cannot be 'Drop Table'
  validates :name, exclusion: {in: ['Drop Table']}

  def must_be_eighteen
    if self.dob && !(Date.today - 18.years  > self.dob)
      self.errors.add(:dob, 'must be older than 18')
    end
  end


  def dog=(dog)
    puts 'hello'
  end

end

app/models/user.rb
require 'digest'

class User < ApplicationRecord

  has_secure_password

  # def authenticate(password)
  #   hashed_password = Digest::SHA256.base64digest(password)
  #   hashed_password == self.password_digest
  # end
  #
  # def password=(password)
  #   hashed_password = Digest::SHA256.base64digest(password)
  #   self.password_digest = hashed_password
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method  :current_user, :logged_in?

  def authorize_user
    if !logged_in?
      flash[:message] = 'You must be logged in to see that page'
      redirect_to login_path
    end
  end

  def current_user

    @current_user ||= User.find_by(id: session[:current_user_id])
    # if @current_user
    #   @current_user
    # else
    #   @current_user = User.find_by(id: session[:current_user_id])
    # end
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    # binding.pry

    if user && user.authenticate(params[:user][:password])
      session[:current_user_id] = user.id
      redirect_to students_path
    else
      flash[:message] = 'We could not find a user with that username in our records or you entered the password incorrectly'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authorize_user, only: [:show, :new]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if !@student.save
      render :new
    else
      redirect_to students_path
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>
  <div class="ui  blue inverted menu">
    <a href="/" class="item">
      <h1>Student Lister</h1>
    </a>
    <div class="right menu">
     <a class="item" href="<%= new_student_path %>">
       Create a New Student
     </a>
     <% if !logged_in? %>
       <%= link_to 'Login', login_path, class: 'item' %>
      <% else %>
        <%= link_to('Log Out', logout_path, method: 'DELETE', class: 'item') %>
      <% end %>
   </div>
  </div>
  <body>
    <div class="ui centered grid ">
      <%= yield %>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<div class='ui six wide column'>
  <h1>All Students</h1>
  <% if logged_in? %>
    <h1>Welcome, <%= current_user.username %></h1>
  <% end %>
  <div class= 'ui huge middle aligned selection divided list'>
    <% @students.each do |student| %>
      <div class="item">
        <%= link_to student.name, student_path(student) %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/new.html.erb
<h1>Create a Student</h1>



<div class="six wide column">
  <% if @student.errors.full_messages.any? %>
    <div class='ui red inverted segment'>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for(@student, html: {class: 'ui form'}) do |f|%>
    <div class="field">
      <label for="">Name</label>
      <%= f.text_field :name, {placeholder: 'Name'} %>
    </div>
    <div class="field">
      <label for="">Email</label>
      <%= f.text_field :email, placeholder: 'Email' %>
    </div>
    <div class="field">
      <label for="">DOB</label>
      <%= f.date_field :dob %>
    </div>
    <div class="field">
      <%= f.submit class: "ui positive massive basic button" %>

    </div>

  <% end %>
</div>

app/views/students/show.html.erb
<div class='ten wide column'>
  <div class='ui raised segment'>
    <div class='ui fluid card'>
      <div class='huge content'>
        <div class='header'><h1><%= @student.name %></h1></div>
        <div class="meta">
           <span class="date">
             <h3><%= @student.dob.to_date %></h3>
           </span>
        </div>
        <div class="description">
          <h3><%= @student.email %></h3>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Back', students_path %>
</div>